In [1]:
#importing libraries
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import math

In [2]:
#load the NSL_KDD dataset
train=pd.read_csv('dataset/KDDTrain+.csv')
test=pd.read_csv('dataset/KDDTest+.csv')

#size of train and test data
print(train.shape,test.shape)

# concatenate traina and test data
dataset=pd.concat([test,train])

#size of whole dataset
print(dataset.shape)

#print(dataset.head(2))
#print(dataset.columns)
X = dataset.iloc[:, :-1].values
print(X)
y = dataset.iloc[:, 41:42].values
print(y)

(113270, 42) (15451, 42)
(128721, 42)
[[0 'tcp' 'private' ... 0.0 1.0 1.0]
 [0 'tcp' 'private' ... 0.0 1.0 1.0]
 [2 'tcp' 'ftp_data' ... 0.0 0.0 0.0]
 ...
 [0 'tcp' 'smtp' ... 0.0 0.01 0.0]
 [0 'tcp' 'klogin' ... 1.0 0.0 0.0]
 [0 'tcp' 'ftp_data' ... 0.0 0.0 0.0]]
[['DDoS']
 ['DDoS']
 ['normal']
 ...
 ['normal']
 ['DDoS']
 ['normal']]


In [3]:
#Encoding of dataset
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1, 2, 3])], remainder = 'passthrough')
X= ct.fit_transform(X)
print(X)

[[0.0 1.0 0.0 ... 0.0 1.0 1.0]
 [0.0 1.0 0.0 ... 0.0 1.0 1.0]
 [0.0 1.0 0.0 ... 0.0 0.0 0.0]
 ...
 [0.0 1.0 0.0 ... 0.0 0.01 0.0]
 [0.0 1.0 0.0 ... 1.0 0.0 0.0]
 [0.0 1.0 0.0 ... 0.0 0.0 0.0]]


In [4]:
from sklearn.preprocessing import LabelEncoder
le_y = LabelEncoder()
y[:, 0] = le_y.fit_transform(y[:, 0])
y= y.astype(int)
y = y.ravel()
print(y)

[0 0 1 ... 1 0 1]


In [5]:
# min_max normalisation between (a,b)
from sklearn.preprocessing import minmax_scale
X = minmax_scale(X, feature_range=(0,1), axis=0)
print(X)

[[0.   1.   0.   ... 0.   1.   1.  ]
 [0.   1.   0.   ... 0.   1.   1.  ]
 [0.   1.   0.   ... 0.   0.   0.  ]
 ...
 [0.   1.   0.   ... 0.   0.01 0.  ]
 [0.   1.   0.   ... 1.   0.   0.  ]
 [0.   1.   0.   ... 0.   0.   0.  ]]


In [6]:
# function to calculate shannon entropy
def cal_entropy(column):
   counts=np.bincount(column)
   probabilites=counts / len(column)
   entropy=0
   for prob in probabilites:
      if(prob)>0:
        entropy+=prob*math.log(prob,2)
   return -entropy 

In [7]:
# function to calculte MedAD adaptive threshold technique
#def thres_MedAd(data):
  #b=1.4826
  #a=3
  #med=np.median(data)
  #MedAd = b*np.median([np.abs(i - med) for i in data])
  #thres=med+a*MedAD
   #return thres

In [8]:
# function to calculte MAD adaptive threshold technique
def thres_MAD(data):
  a=5.5
  from numpy import mean, absolute
  MAD =mean(absolute(data - mean(data)))
  thres= mean(data)+a*MAD
  return thres

In [9]:
print(X.shape)
num_Of_Columns = X.shape[1]
print("num_Of_Columns",num_Of_Columns)

(128721, 116)
num_Of_Columns 116


In [10]:
# form a list of attribute that has to deleted further

list=[]
for j in range(0,num_Of_Columns) :
        col=np.array(X[:,j])
        col=col.astype(int)
        if  cal_entropy(col)<thres_MAD(col) :
            list.append(j)
print(list)         
print(len(list))





[0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 45, 47, 52, 53, 54, 55, 56, 57, 58, 61, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 76, 82, 86, 88, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 110, 111, 112, 113, 114, 115]
87


In [11]:
print(X.shape,y.shape)

(128721, 116) (128721,)


In [12]:
# delete the attribute that have less entropy than adaptive threshold value(THR)
X = np.delete(X, list, axis=1)

In [13]:
print(X.shape)

(128721, 29)


In [14]:
# splitting of dataset in train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state =42)
print(X_train)
print(X_test)
print(y_train)
print(y_test)


[[0.   0.   0.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 0.   0.   0.04]
 [0.   0.   0.   ... 0.   0.   0.02]
 ...
 [0.   0.   0.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 0.   0.   0.  ]]
[[0.   0.   0.   ... 0.   0.   0.07]
 [0.   0.   0.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 0.   0.   0.07]
 ...
 [0.   0.   0.   ... 0.   0.   0.02]
 [0.   0.   0.   ... 0.   0.   0.19]
 [0.   0.   0.   ... 0.   0.   0.  ]]
[1 0 0 ... 1 1 1]
[0 1 0 ... 1 1 1]


In [15]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

In [16]:
# base classifier RandomForest
y_train = y_train.ravel()
clf1 = RandomForestClassifier(n_estimators=100)
clf1.fit(X_train, y_train)
y_pred1 = clf1.predict(X_test)
from pandas_ml import ConfusionMatrix
cm = ConfusionMatrix(y_test, y_pred1)
cm.print_stats()
#Root mean square error between actual and predicted class
from sklearn.metrics import mean_squared_error
from math import sqrt
RMSE = sqrt(mean_squared_error(y_test, y_pred1))
print("RMSE= ",RMSE)


population: 25745
P: 15363
N: 10382
PositiveTest: 15149
NegativeTest: 10596
TP: 15064
TN: 10297
FP: 85
FN: 299
TPR: 0.9805376554058453
TNR: 0.9918127528414563
PPV: 0.9943890685853852
NPV: 0.9717818044545111
FPR: 0.008187247158543633
FDR: 0.005610931414614826
FNR: 0.019462344594154787
ACC: 0.9850844824237716
F1_score: 0.9874147876245412
MCC: 0.969255715916597
informedness: 0.9723504082473016
markedness: 0.9661708730398963
prevalence: 0.5967372305302
LRP: 119.76402280498219
LRN: 0.01962300296945858
DOR: 6103.2464292740515
FOR: 0.028218195545488864
RMSE=  0.12212910208557334


In [17]:
# base classifier GradientBoosting
clf2 = GradientBoostingClassifier(n_estimators=100)
clf2.fit(X_train, y_train)
y_pred2 = clf2.predict(X_test)
from pandas_ml import ConfusionMatrix
cm = ConfusionMatrix(y_test, y_pred2)
cm.print_stats()
#Root mean square error between actual and predicted class
from sklearn.metrics import mean_squared_error
from math import sqrt
RMSE = sqrt(mean_squared_error(y_test, y_pred2))
print("RMSE= ",RMSE)

population: 25745
P: 15363
N: 10382
PositiveTest: 15120
NegativeTest: 10625
TP: 15014
TN: 10276
FP: 106
FN: 349
TPR: 0.9772830827312374
TNR: 0.9897900211905221
PPV: 0.992989417989418
NPV: 0.9671529411764705
FPR: 0.010209978809477943
FDR: 0.0070105820105820105
FNR: 0.022716917268762613
ACC: 0.9823266653719169
F1_score: 0.9850736476068629
MCC: 0.9636015003544343
informedness: 0.9670731039217595
markedness: 0.9601423591658884
prevalence: 0.5967372305302
LRP: 95.71842419731799
LRN: 0.022951249035061645
DOR: 4170.510461155863
FOR: 0.03284705882352941
RMSE=  0.1329410945798293


In [18]:
# SVM
from sklearn.svm import SVC  
clf3= SVC(kernel='linear') 
clf3.fit(X_train, y_train) 
y_pred3 = clf3.predict(X_test)

from pandas_ml import ConfusionMatrix
cm = ConfusionMatrix(y_test, y_pred3)
cm.print_stats()
#Root mean square error between actual and predicted class
from sklearn.metrics import mean_squared_error
from math import sqrt
RMSE = sqrt(mean_squared_error(y_test, y_pred3))
print("RMSE= ",RMSE)

population: 25745
P: 15363
N: 10382
PositiveTest: 15024
NegativeTest: 10721
TP: 13506
TN: 8864
FP: 1518
FN: 1857
TPR: 0.8791251708650654
TNR: 0.8537853978038914
PPV: 0.8989616613418531
NPV: 0.826788545844604
FPR: 0.14621460219610866
FDR: 0.10103833865814696
FNR: 0.12087482913493458
ACC: 0.8689065838026802
F1_score: 0.8889327673018067
MCC: 0.7293216005718186
informedness: 0.7329105686689568
markedness: 0.725750207186457
prevalence: 0.5967372305302
LRP: 6.0125675388149595
LRN: 0.1415751890883225
DOR: 42.46907652063233
FOR: 0.17321145415539596
RMSE=  0.36206824798278


In [28]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
clf4 = KNeighborsClassifier(n_neighbors =19)
clf4.fit(X_train, y_train) 
y_pred4 = clf4.predict(X_test)

from pandas_ml import ConfusionMatrix
cm = ConfusionMatrix(y_test, y_pred4)
cm.print_stats()
#Root mean square error between actual and predicted class
from sklearn.metrics import mean_squared_error
from math import sqrt
RMSE = sqrt(mean_squared_error(y_test, y_pred4))
print("RMSE= ",RMSE)

population: 25745
P: 15363
N: 10382
PositiveTest: 15321
NegativeTest: 10424
TP: 15209
TN: 10270
FP: 112
FN: 154
TPR: 0.9899759161622079
TNR: 0.9892120978616837
PPV: 0.9926897722080804
NPV: 0.9852264006139677
FPR: 0.010787902138316317
FDR: 0.007310227791919587
FNR: 0.010024083837792097
ACC: 0.9896678966789668
F1_score: 0.9913309868335288
MCC: 0.9785518867936774
informedness: 0.9791880140238916
markedness: 0.9779161728220482
prevalence: 0.5967372305302
LRP: 91.76723179996466
LRN: 0.010133401986753414
DOR: 9055.91546846011
FOR: 0.014773599386032234
RMSE=  0.10164695431262666


In [20]:
# meta classifier LogisticRegression
lr = LogisticRegression(solver='lbfgs')


In [29]:
from mlxtend.classifier import StackingClassifier
sclf = StackingClassifier(classifiers=[clf1, clf2,clf4],meta_classifier=lr,use_probas = True, use_features_in_secondary = True)

In [30]:
# train and test the model
sclf.fit(X_train, y_train)
y_pred = sclf.predict(X_test)
from pandas_ml import ConfusionMatrix
cm = ConfusionMatrix(y_test, y_pred)
cm.print_stats()
#Root mean square error between actual and predicted class
from sklearn.metrics import mean_squared_error
from math import sqrt
RMSE = sqrt(mean_squared_error(y_test, y_pred))
print("RMSE= ",RMSE)



population: 25745
P: 15363
N: 10382
PositiveTest: 15363
NegativeTest: 10382
TP: 15280
TN: 10299
FP: 83
FN: 83
TPR: 0.9945974093601511
TNR: 0.9920053939510691
PPV: 0.9945974093601511
NPV: 0.9920053939510691
FPR: 0.007994606048930842
FDR: 0.005402590639848988
FNR: 0.005402590639848988
ACC: 0.9935521460477763
F1_score: 0.9945974093601511
MCC: 0.9866028033112202
informedness: 0.9866028033112202
markedness: 0.9866028033112202
prevalence: 0.5967372305302
LRP: 124.40855787924203
LRN: 0.0054461303061377015
DOR: 22843.47800841922
FOR: 0.007994606048930842
RMSE=  0.0802985301996477
